### ISSUE TITLE
Unable to locate TMC2209.h file in your directory.

### ISSUE THREAD

**Issue by ZillKhan** [janelia-arduino/TMC429#6]
Hello, 
I am unable to locate the TMC2209.h and TMC2209.cpp files in src folder.

**Comment by peterpolidoro** [comment]
Hi,

I am not quite sure I know what you mean. How did you download the library and where are you looking?

**Comment by ZillKhan** [comment]
I download the library using `download zip` option in code menu.

**Comment by peterpolidoro** [comment]
How are you unzipping the archive? Do you see any files from the unzipped archive?

I correctly see the files when I run the command:

`cd /tmp/ && wget https://github.com/janelia-arduino/TMC429/archive/refs/tags/1.3.4.zip -O tmc429.zip && unzip -l tmc429.zip`

> Archive:  tmc429.zip
> 
> 7d2596037ef0f3603536d9252cd2dbe38b291db2
>   Length      Date    Time    Name
> ---------  ---------- -----   ----
>         0  2022-09-30 11:23   TMC429-1.3.4/
>        87  2022-09-30 11:23   TMC429-1.3.4/.gitignore
>      1517  2022-09-30 11:23   TMC429-1.3.4/LICENSE
>      2322  2022-09-30 11:23   TMC429-1.3.4/README.org
>         0  2022-09-30 11:23   TMC429-1.3.4/examples/
>         0  2022-09-30 11:23   TMC429-1.3.4/examples/Communicating/
>       539  2022-09-30 11:23   TMC429-1.3.4/examples/Communicating/Communicating.ino
>         0  2022-09-30 11:23   TMC429-1.3.4/examples/Communicating_ESP32/
>      1749  2022-09-30 11:23   TMC429-1.3.4/examples/Communicating_ESP32/Communicating_ESP32.ino
>         0  2022-09-30 11:23   TMC429-1.3.4/examples/Limits/
>      1292  2022-09-30 11:23   TMC429-1.3.4/examples/Limits/Limits.ino
>         0  2022-09-30 11:23   TMC429-1.3.4/examples/TMC2209/
>      3730  2022-09-30 11:23   TMC429-1.3.4/examples/TMC2209/TMC2209.ino
>         0  2022-09-30 11:23   TMC429-1.3.4/examples/TMC429_TMC26X_EVAL/
>      2307  2022-09-30 11:23   TMC429-1.3.4/examples/TMC429_TMC26X_EVAL/TMC429_TMC26X_EVAL.ino
>         0  2022-09-30 11:23   TMC429-1.3.4/examples/TestConnection/
>      7135  2022-09-30 11:23   TMC429-1.3.4/examples/TestConnection/TestConnection.ino
>         0  2022-09-30 11:23   TMC429-1.3.4/images/
>     45192  2022-09-30 11:23   TMC429-1.3.4/images/TMC429.png
>     46120  2022-09-30 11:23   TMC429-1.3.4/images/block_diagram.png
>     17054  2022-09-30 11:23   TMC429-1.3.4/images/stepper_controller.png
>     19765  2022-09-30 11:23   TMC429-1.3.4/images/stepper_driver.png
>       362  2022-09-30 11:23   TMC429-1.3.4/library.properties
>         0  2022-09-30 11:23   TMC429-1.3.4/src/
>     28252  2022-09-30 11:23   TMC429-1.3.4/src/TMC429.cpp
>     11666  2022-09-30 11:23   TMC429-1.3.4/src/TMC429.h
> ---------                     -------
>    189089                     26 files

**Comment by ZillKhan** [comment]
I completely agree here I see the same directory when I also unzip the `tmc429.zip`
But it doesn't contain `<TMC2209.h>` that is being included in `TMC2209.ino`

![image](https://user-images.githubusercontent.com/52318632/206631610-c14828cd-7902-4837-a04d-de27db06ae42.png)

Can you help me here with where am I missing in finding this TMC2209.h file?
I am also unable to find this header file in the directory structure you have shared.

**Comment by peterpolidoro** [comment]
Ah yes, sorry I read your issue too quickly and missed that you were talking about TMC2209, not TMC429. The TMC2209 files are in another repository:

[https://github.com/janelia-arduino/TMC2209](https://github.com/janelia-arduino/TMC2209)

I will add a link in the documentation if there is not one already. Sorry for the confusion!

**Comment by ZillKhan** [comment]
Thank you for your help.
